<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PropertyImages\**" />
    <EmbeddedResource Remove="PropertyImages\**" />
    <None Remove="PropertyImages\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealEstate.Domain\RealEstate.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\Commands\DeleteProperty\" />
    <Folder Include="Properties\Commands\ChangePropertyStatus\" />
    <Folder Include="Properties\Commands\PublishProperty\" />
    <Folder Include="Properties\Commands\UpdateProperty\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
  </ItemGroup>

</Project>
